apiVersion: v1
kind: Service
metadata:
  name: delivery
  namespace: istio-cb-ns
  labels:
    app: delivery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: delivery
